package domain;
// Generated 08-may-2019 9:56:30 by Hibernate Tools 5.4.1.Final

import java.util.HashSet;
import java.util.Set;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import dataAccess.HibernateDataAccess;

/**
 * Erabiltzailea generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class Erabiltzailea implements java.io.Serializable {

	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private Integer idErabiltzailea=0;
	
	@XmlIDREF
	private Komunitatea komunitatea=new Komunitatea();
	
	private String nick="";
	private String email="";
	private String pasahitza="";
	private String izenOsoa="";
	private int dirua=0;
	private boolean administratzailea=false;
	private String hizkuntza="eu";
	private int koloreak=0;
	private int orduDiferentzia=6;
	
	@XmlIDREF private Set eskaintzas = new HashSet(0);
	@XmlIDREF private Set jokalarias = new HashSet(0);
	@XmlIDREF private Set puntuazioaErabiltzaileaJardunaldias = new HashSet(0);
	@XmlIDREF private Set merkatukoJokalariasForIdErabiltzaileaIrabazlea = new HashSet(0);
	@XmlIDREF private Set merkatukoJokalariasForIdErabiltzaileaJabea = new HashSet(0);
	@XmlIDREF private Set mezuas = new HashSet(0);
	@XmlIDREF private Set transakzioas = new HashSet(0);
	@XmlIDREF private Set alineazioas = new HashSet(0);

	public Erabiltzailea() {
	}
	
	public Erabiltzailea getKopia() {
		Erabiltzailea res=new Erabiltzailea();
		try{res.setIdErabiltzailea(idErabiltzailea);}catch(Exception e) {e.printStackTrace();}
		try{res.setKomunitatea(komunitatea.getKopia());}catch(Exception e) {e.printStackTrace();}
		try{res.setNick(nick);}catch(Exception e) {e.printStackTrace();}
		try{res.setEmail(email);}catch(Exception e) {e.printStackTrace();}
		try{res.setPasahitza(pasahitza);}catch(Exception e) {e.printStackTrace();}
		try{res.setIzenOsoa(izenOsoa);}catch(Exception e) {e.printStackTrace();}
		try{res.setDirua(dirua);}catch(Exception e) {e.printStackTrace();}
		try{res.setAdministratzailea(administratzailea);}catch(Exception e) {e.printStackTrace();}
		try{res.setHizkuntza(hizkuntza);}catch(Exception e) {e.printStackTrace();}
		try{res.setKoloreak(koloreak);}catch(Exception e) {e.printStackTrace();}
		try{res.setOrduDiferentzia(orduDiferentzia);}catch(Exception e) {e.printStackTrace();}
		return res;
	}
	

	public Erabiltzailea(int idErabiltzailea) {
		this.idErabiltzailea=idErabiltzailea;
	}
	
	public Erabiltzailea(String nick, String email, String pasahitza, String izenOsoa, int dirua,
			boolean administratzailea, String hizkuntza, int koloreak, int orduDiferentzia) {
		this.nick = nick;
		this.email = email;
		this.pasahitza = pasahitza;
		this.izenOsoa = izenOsoa;
		this.dirua = dirua;
		this.administratzailea = administratzailea;
		this.hizkuntza = hizkuntza;
		this.koloreak = koloreak;
		this.orduDiferentzia = orduDiferentzia;
	}

	public Erabiltzailea(Komunitatea komunitatea, String nick, String email, String pasahitza, String izenOsoa,
			int dirua, boolean administratzailea, String hizkuntza, int koloreak, int orduDiferentzia, Set eskaintzas,
			Set jokalarias, Set puntuazioaErabiltzaileaJardunaldias, Set merkatukoJokalariasForIdErabiltzaileaIrabazlea,
			Set merkatukoJokalariasForIdErabiltzaileaJabea, Set mezuas, Set transakzioas, Set alineazioas) {
		this.komunitatea = komunitatea;
		this.nick = nick;
		this.email = email;
		this.pasahitza = pasahitza;
		this.izenOsoa = izenOsoa;
		this.dirua = dirua;
		this.administratzailea = administratzailea;
		this.hizkuntza = hizkuntza;
		this.koloreak = koloreak;
		this.orduDiferentzia = orduDiferentzia;
		this.eskaintzas = eskaintzas;
		this.jokalarias = jokalarias;
		this.puntuazioaErabiltzaileaJardunaldias = puntuazioaErabiltzaileaJardunaldias;
		this.merkatukoJokalariasForIdErabiltzaileaIrabazlea = merkatukoJokalariasForIdErabiltzaileaIrabazlea;
		this.merkatukoJokalariasForIdErabiltzaileaJabea = merkatukoJokalariasForIdErabiltzaileaJabea;
		this.mezuas = mezuas;
		this.transakzioas = transakzioas;
		this.alineazioas = alineazioas;
	}

	
	public void jokalariakEsleitu() {
		int kop=0;
		HibernateDataAccess dbManager = new HibernateDataAccess();
		Set<Jokalaria> jokalariak = dbManager.komunitatekoJokalariaLibreakLortu(komunitatea);
		
		for(Jokalaria jokalaria: jokalariak) {
			if(jokalaria.getSoldata()> 25000000 && !this.getJokalarias().contains(jokalaria)) {
				this.jokalarias.add(jokalaria);break;
			}
		}
		for(Jokalaria jokalaria: jokalariak) {
			if(jokalaria.getSoldata()> 15000000 && jokalaria.getSoldata()< 25000000 && !this.getJokalarias().contains(jokalaria) ) {
				this.jokalarias.add(jokalaria);
				if(kop==1) {kop=0;break;}else{kop++;}
			}
		}
		for(Jokalaria jokalaria: jokalariak) {
			if(jokalaria.getSoldata()> 5000000 && jokalaria.getSoldata()< 15000000 && !this.getJokalarias().contains(jokalaria)) {
				this.jokalarias.add(jokalaria);
				if(kop==2) {kop=0;break;}else{kop++;}
			}
		}
		for(Jokalaria jokalaria: jokalariak) {
			if(!this.getJokalarias().contains(jokalaria)) {
				this.jokalarias.add(jokalaria);
				if(kop==3) {kop=0;break;}else{kop++;}
			}
		}
	}
	
	
	public Integer getIdErabiltzailea() {
		return this.idErabiltzailea;
	}

	public void setIdErabiltzailea(Integer idErabiltzailea) {
		this.idErabiltzailea = idErabiltzailea;
	}

	public Komunitatea getKomunitatea() {
		return this.komunitatea;
	}

	public void setKomunitatea(Komunitatea komunitatea) {
		this.komunitatea = komunitatea;
	}

	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasahitza() {
		return this.pasahitza;
	}

	public void setPasahitza(String pasahitza) {
		this.pasahitza = pasahitza;
	}

	public String getIzenOsoa() {
		return this.izenOsoa;
	}

	public void setIzenOsoa(String izenOsoa) {
		this.izenOsoa = izenOsoa;
	}

	public int getDirua() {
		return this.dirua;
	}

	public void setDirua(int dirua) {
		this.dirua = dirua;
	}

	public boolean isAdministratzailea() {
		return this.administratzailea;
	}

	public void setAdministratzailea(boolean administratzailea) {
		this.administratzailea = administratzailea;
	}

	public String getHizkuntza() {
		return this.hizkuntza;
	}

	public void setHizkuntza(String hizkuntza) {
		this.hizkuntza = hizkuntza;
	}

	public int getKoloreak() {
		return this.koloreak;
	}

	public void setKoloreak(int koloreak) {
		this.koloreak = koloreak;
	}

	public int getOrduDiferentzia() {
		return this.orduDiferentzia;
	}

	public void setOrduDiferentzia(int orduDiferentzia) {
		this.orduDiferentzia = orduDiferentzia;
	}

	public Set getJokalarias() {
		return this.jokalarias;
	}

	public void setJokalarias(Set jokalarias) {
		this.jokalarias = jokalarias;
	}
	
	public Set getEskaintzas() {
		return this.eskaintzas;
	}

	public void setEskaintzas(Set eskaintzas) {
		this.eskaintzas = eskaintzas;
	}

	public Set getPuntuazioaErabiltzaileaJardunaldias() {
		return this.puntuazioaErabiltzaileaJardunaldias;
	}

	public void setPuntuazioaErabiltzaileaJardunaldias(Set puntuazioaErabiltzaileaJardunaldias) {
		this.puntuazioaErabiltzaileaJardunaldias = puntuazioaErabiltzaileaJardunaldias;
	}

	public Set getMerkatukoJokalariasForIdErabiltzaileaIrabazlea() {
		return this.merkatukoJokalariasForIdErabiltzaileaIrabazlea;
	}

	public void setMerkatukoJokalariasForIdErabiltzaileaIrabazlea(Set merkatukoJokalariasForIdErabiltzaileaIrabazlea) {
		this.merkatukoJokalariasForIdErabiltzaileaIrabazlea = merkatukoJokalariasForIdErabiltzaileaIrabazlea;
	}

	public Set getMerkatukoJokalariasForIdErabiltzaileaJabea() {
		return this.merkatukoJokalariasForIdErabiltzaileaJabea;
	}

	public void setMerkatukoJokalariasForIdErabiltzaileaJabea(Set merkatukoJokalariasForIdErabiltzaileaJabea) {
		this.merkatukoJokalariasForIdErabiltzaileaJabea = merkatukoJokalariasForIdErabiltzaileaJabea;
	}

	public Set getMezuas() {
		return this.mezuas;
	}

	public void setMezuas(Set mezuas) {
		this.mezuas = mezuas;
	}

	public Set getTransakzioas() {
		return this.transakzioas;
	}

	public void setTransakzioas(Set transakzioas) {
		this.transakzioas = transakzioas;
	}

	public Set getAlineazioas() {
		return this.alineazioas;
	}

	public void setAlineazioas(Set alineazioas) {
		this.alineazioas = alineazioas;
	}

}
