package domain;
// Generated 08-may-2019 9:56:30 by Hibernate Tools 5.4.1.Final

import java.util.HashSet;
import java.util.Set;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Erabiltzailea generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class Eskaintza implements java.io.Serializable {

	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private Integer idEskaintza=0;
	
	@XmlIDREF private Erabiltzailea erabiltzailea=null;
	private MerkatukoJokalaria merkatukoJokalaria=new MerkatukoJokalaria();
	
	private int eskaintza=0;

	public Eskaintza() {
	}
	
	public Eskaintza getKopia() {
		Eskaintza res=new Eskaintza();
		res.setIdEskaintza(idEskaintza);
		res.setErabiltzailea(erabiltzailea.getKopia());
		res.setMerkatukoJokalaria(merkatukoJokalaria.getKopia());
		res.setEskaintza(eskaintza);
		return res;
	}

	public Eskaintza(int idEskaintza, Erabiltzailea erabiltzailea, MerkatukoJokalaria merkatukoJokalaria, int eskaintza) {
		this.idEskaintza=idEskaintza;
		this.erabiltzailea = erabiltzailea;
		this.merkatukoJokalaria = merkatukoJokalaria;
		this.eskaintza = eskaintza;
	}
	
	public Eskaintza(Erabiltzailea erabiltzailea, MerkatukoJokalaria merkatukoJokalaria, int eskaintza) {
		this.erabiltzailea = erabiltzailea;
		this.merkatukoJokalaria = merkatukoJokalaria;
		this.eskaintza = eskaintza;
	}

	public Integer getIdEskaintza() {
		return this.idEskaintza;
	}

	public void setIdEskaintza(Integer idEskaintza) {
		this.idEskaintza = idEskaintza;
	}

	public Erabiltzailea getErabiltzailea() {
		return this.erabiltzailea;
	}

	public void setErabiltzailea(Erabiltzailea erabiltzailea) {
		this.erabiltzailea = erabiltzailea;
	}

	public MerkatukoJokalaria getMerkatukoJokalaria() {
		return this.merkatukoJokalaria;
	}

	public void setMerkatukoJokalaria(MerkatukoJokalaria merkatukoJokalaria) {
		this.merkatukoJokalaria = merkatukoJokalaria;
	}

	public int getEskaintza() {
		return this.eskaintza;
	}

	public void setEskaintza(int eskaintza) {
		this.eskaintza = eskaintza;
	}

}
