package domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Jardunaldia generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class Jardunaldia implements Serializable {
	
	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private Integer idJardunaldia;
	private Date hasierakoEguna;
	
	@XmlIDREF private Set puntuazioaJokalariaJardunaldias = new HashSet(0);
	@XmlIDREF private Set puntuazioaErabiltzaileaJardunaldias = new HashSet(0);

	public Jardunaldia() {
	}
	
	public Jardunaldia getKopia() {
		Jardunaldia res=new Jardunaldia();
		res.setIdJardunaldia(idJardunaldia);
		res.setHasierakoEguna(hasierakoEguna);
		return res;
	}
	

	public Jardunaldia(Date hasierakoEguna, Set puntuazioaJokalariaJardunaldias,
			Set puntuazioaErabiltzaileaJardunaldias) {
		this.hasierakoEguna = hasierakoEguna;
		this.puntuazioaJokalariaJardunaldias = puntuazioaJokalariaJardunaldias;
		this.puntuazioaErabiltzaileaJardunaldias = puntuazioaErabiltzaileaJardunaldias;
	}

	public Integer getIdJardunaldia() {
		return this.idJardunaldia;
	}

	public void setIdJardunaldia(Integer idJardunaldia) {
		this.idJardunaldia = idJardunaldia;
	}

	public Date getHasierakoEguna() {
		return this.hasierakoEguna;
	}

	public void setHasierakoEguna(Date hasierakoEguna) {
		this.hasierakoEguna = hasierakoEguna;
	}

	public Set getPuntuazioaJokalariaJardunaldias() {
		return this.puntuazioaJokalariaJardunaldias;
	}

	public void setPuntuazioaJokalariaJardunaldias(Set puntuazioaJokalariaJardunaldias) {
		this.puntuazioaJokalariaJardunaldias = puntuazioaJokalariaJardunaldias;
	}

	public Set getPuntuazioaErabiltzaileaJardunaldias() {
		return this.puntuazioaErabiltzaileaJardunaldias;
	}

	public void setPuntuazioaErabiltzaileaJardunaldias(Set puntuazioaErabiltzaileaJardunaldias) {
		this.puntuazioaErabiltzaileaJardunaldias = puntuazioaErabiltzaileaJardunaldias;
	}

}
