package domain;
// Generated 08-may-2019 9:56:30 by Hibernate Tools 5.4.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import dataAccess.HibernateDataAccess;


/**
 * Jokalaria generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class Jokalaria implements java.io.Serializable {

	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private Integer idJokalaria=0;
	
	@XmlIDREF private Taldea taldeaByIdTaldea=new Taldea();
	@XmlIDREF private Taldea taldeaByDraftIdTaldea=new Taldea();
	
	private String izena="";
	private String abizena="";
	private Integer dortsala=0;
	private String posizioa="";
	private Float altuera=0f;
	private Float pisua=0f;
	private Date jaiotzeData=new Date();
	private String nazionalitatea="";
	private Integer draftUrtea=0;
	private Integer draftPostua=0;
	private String unibertsitatea="";
	private Integer nbaDebutUrtea=0;
	private Integer nbaUrteak=0;
	private int soldata=0;
	
	@XmlIDREF private Set puntuazioaJokalariaJardunaldias = new HashSet(0);
	@XmlIDREF private Set erabiltzaileas = new HashSet(0);
	@XmlIDREF private Set alineazioasForIdJokalaria5 = new HashSet(0);
	@XmlIDREF private Set alineazioasForIdJokalaria4 = new HashSet(0);
	@XmlIDREF private Set alineazioasForIdJokalaria3 = new HashSet(0);
	@XmlIDREF private Set alineazioasForIdJokalaria2 = new HashSet(0);
	@XmlIDREF private Set alineazioasForIdJokalaria1 = new HashSet(0);
	@XmlIDREF private Set merkatukoJokalarias = new HashSet(0);

	public Jokalaria() {
	}
	
	public Jokalaria getKopia() {
		Jokalaria res=new Jokalaria();
		res.setIdJokalaria(idJokalaria);
		res.setTaldeaByIdTaldea(taldeaByIdTaldea.getKopia());
		try{res.setTaldeaByDraftIdTaldea(taldeaByDraftIdTaldea.getKopia());}catch(Exception e) {}
		res.setIzena(izena);
		res.setAbizena(abizena);
		res.setDortsala(dortsala);
		res.setPosizioa(posizioa);
		res.setAltuera(altuera);
		res.setPisua(pisua);
		res.setJaiotzeData(jaiotzeData);
		res.setNazionalitatea(nazionalitatea);
		res.setDraftPostua(draftPostua);
		res.setDraftUrtea(draftUrtea);
		res.setUnibertsitatea(unibertsitatea);
		res.setNbaDebutUrtea(nbaDebutUrtea);
		res.setNbaUrteak(nbaUrteak);
		res.setSoldata(soldata);
		return res;
	}

	public Jokalaria(int idJokalaria) {
		this.idJokalaria = idJokalaria;
	}
	public Jokalaria(int idJokalaria, int soldata) {
		this.idJokalaria = idJokalaria;
		this.soldata = soldata;
	}
	
	public String izenOsoa(){
		try{
			return this.izena+" "+this.abizena;
		}catch (Exception e){
			return "";
		}
	}

	public Jokalaria(int idJokalaria, Taldea taldeaByIdTaldea, Taldea taldeaByDraftIdTaldea, String izena,
			String abizena, Integer dortsala, String posizioa, Float altuera, Float pisua, Date jaiotzeData,
			String nazionalitatea, Integer draftUrtea, Integer draftPostua, String unibertsitatea,
			Integer nbaDebutUrtea, Integer nbaUrteak, int soldata, Set puntuazioaJokalariaJardunaldias,
			Set erabiltzaileas, Set alineazioasForIdJokalaria5, Set alineazioasForIdJokalaria4,
			Set alineazioasForIdJokalaria3, Set alineazioasForIdJokalaria2, Set merkatukoJokalarias,
			Set alineazioasForIdJokalaria1) {
		this.idJokalaria = idJokalaria;
		this.taldeaByIdTaldea = taldeaByIdTaldea;
		this.taldeaByDraftIdTaldea = taldeaByDraftIdTaldea;
		this.izena = izena;
		this.abizena = abizena;
		this.dortsala = dortsala;
		this.posizioa = posizioa;
		this.altuera = altuera;
		this.pisua = pisua;
		this.jaiotzeData = jaiotzeData;
		this.nazionalitatea = nazionalitatea;
		this.draftUrtea = draftUrtea;
		this.draftPostua = draftPostua;
		this.unibertsitatea = unibertsitatea;
		this.nbaDebutUrtea = nbaDebutUrtea;
		this.nbaUrteak = nbaUrteak;
		this.soldata = soldata;
		this.puntuazioaJokalariaJardunaldias = puntuazioaJokalariaJardunaldias;
		this.erabiltzaileas = erabiltzaileas;
		this.alineazioasForIdJokalaria5 = alineazioasForIdJokalaria5;
		this.alineazioasForIdJokalaria4 = alineazioasForIdJokalaria4;
		this.alineazioasForIdJokalaria3 = alineazioasForIdJokalaria3;
		this.alineazioasForIdJokalaria2 = alineazioasForIdJokalaria2;
		this.merkatukoJokalarias = merkatukoJokalarias;
		this.alineazioasForIdJokalaria1 = alineazioasForIdJokalaria1;
	}
	
	
	
	public boolean antzekoa_den_konprobatu(String izen,String abizen) {
		String izen_lag=textu_soila_bihurtu(izen);
		String abizen_lag=textu_soila_bihurtu(abizen);
		
		String izena=textu_soila_bihurtu(this.izena);
		String abizena=textu_soila_bihurtu(this.abizena);
		
		if(izen_lag.charAt(0)==izena.charAt(0) && abizen_lag.contains(abizena) || izena.charAt(0)==izen_lag.charAt(0) && abizena.contains(abizen_lag)) {
			return true;
		}
		return false;
	}
	public boolean jokalaria_den_konprobatu(String izen,String abizen) {
		String izen_lag=textu_soila_bihurtu(izen);
		String abizen_lag=textu_soila_bihurtu(abizen);
		
		String izena=textu_soila_bihurtu(this.izena);
		String abizena=textu_soila_bihurtu(this.abizena);
		
		if(izen_lag.contains(izena) && abizen_lag.contains(abizena) || izena.contains(izen_lag) && abizena.contains(abizen_lag) ) {
			return true;
		}
		return false;
	}
	private String textu_soila_bihurtu(String izena) {

		return izena.toLowerCase().replace("'","").replace(".","").replace("’", "")
                .replace("á", "a").replace("à", "a").replace("ä", "a")
                .replace("é", "e").replace("è", "e").replace("ë", "e").replace("ê", "e")
                .replace("í", "i").replace("ì", "i").replace("ï", "i")
                .replace("ó", "o").replace("ò", "o").replace("ö", "o")
                .replace("ú", "u").replace("ù", "u").replace("ü", "u")
                .replace(" jr", "")
                //.replace(" iii", "").replace(" iv", "")
                ;
	}
	

	public int getIdJokalaria() {
		return this.idJokalaria;
	}

	public void setIdJokalaria(int idJokalaria) {
		this.idJokalaria = idJokalaria;
	}

	public Taldea getTaldeaByIdTaldea() {
		return this.taldeaByIdTaldea;
	}

	public void setTaldeaByIdTaldea(Taldea taldeaByIdTaldea) {
		this.taldeaByIdTaldea = taldeaByIdTaldea;
	}

	public Taldea getTaldeaByDraftIdTaldea() {
		return this.taldeaByDraftIdTaldea;
	}

	public void setTaldeaByDraftIdTaldea(Taldea taldeaByDraftIdTaldea) {
		this.taldeaByDraftIdTaldea = taldeaByDraftIdTaldea;
	}

	public String getIzena() {
		return this.izena;
	}

	public void setIzena(String izena) {
		this.izena = izena;
	}

	public String getAbizena() {
		return this.abizena;
	}

	public void setAbizena(String abizena) {
		this.abizena = abizena;
	}

	public Integer getDortsala() {
		return this.dortsala;
	}

	public void setDortsala(Integer dortsala) {
		this.dortsala = dortsala;
	}

	public String getPosizioa() {
		return this.posizioa;
	}

	public void setPosizioa(String posizioa) {
		this.posizioa = posizioa;
	}

	public Float getAltuera() {
		return this.altuera;
	}

	public void setAltuera(Float altuera) {
		this.altuera = altuera;
	}

	public Float getPisua() {
		return this.pisua;
	}

	public void setPisua(Float pisua) {
		this.pisua = pisua;
	}

	public Date getJaiotzeData() {
		return this.jaiotzeData;
	}

	public void setJaiotzeData(Date jaiotzeData) {
		this.jaiotzeData = jaiotzeData;
	}

	public String getNazionalitatea() {
		return this.nazionalitatea;
	}

	public void setNazionalitatea(String nazionalitatea) {
		this.nazionalitatea = nazionalitatea;
	}

	public Integer getDraftUrtea() {
		return this.draftUrtea;
	}

	public void setDraftUrtea(Integer draftUrtea) {
		this.draftUrtea = draftUrtea;
	}

	public Integer getDraftPostua() {
		return this.draftPostua;
	}

	public void setDraftPostua(Integer draftPostua) {
		this.draftPostua = draftPostua;
	}

	public String getUnibertsitatea() {
		return this.unibertsitatea;
	}

	public void setUnibertsitatea(String unibertsitatea) {
		this.unibertsitatea = unibertsitatea;
	}

	public Integer getNbaDebutUrtea() {
		return this.nbaDebutUrtea;
	}

	public void setNbaDebutUrtea(Integer nbaDebutUrtea) {
		this.nbaDebutUrtea = nbaDebutUrtea;
	}

	public Integer getNbaUrteak() {
		return this.nbaUrteak;
	}

	public void setNbaUrteak(Integer nbaUrteak) {
		this.nbaUrteak = nbaUrteak;
	}

	public int getSoldata() {
		return this.soldata;
	}

	public void setSoldata(int soldata) {
		this.soldata = soldata;
	}

	public Set getPuntuazioaJokalariaJardunaldias() {
		return this.puntuazioaJokalariaJardunaldias;
	}

	public void setPuntuazioaJokalariaJardunaldias(Set puntuazioaJokalariaJardunaldias) {
		this.puntuazioaJokalariaJardunaldias = puntuazioaJokalariaJardunaldias;
	}

	public Set getErabiltzaileas() {
		return this.erabiltzaileas;
	}

	public void setErabiltzaileas(Set erabiltzaileas) {
		this.erabiltzaileas = erabiltzaileas;
	}

	public Set getAlineazioasForIdJokalaria5() {
		return this.alineazioasForIdJokalaria5;
	}

	public void setAlineazioasForIdJokalaria5(Set alineazioasForIdJokalaria5) {
		this.alineazioasForIdJokalaria5 = alineazioasForIdJokalaria5;
	}

	public Set getAlineazioasForIdJokalaria4() {
		return this.alineazioasForIdJokalaria4;
	}

	public void setAlineazioasForIdJokalaria4(Set alineazioasForIdJokalaria4) {
		this.alineazioasForIdJokalaria4 = alineazioasForIdJokalaria4;
	}

	public Set getAlineazioasForIdJokalaria3() {
		return this.alineazioasForIdJokalaria3;
	}

	public void setAlineazioasForIdJokalaria3(Set alineazioasForIdJokalaria3) {
		this.alineazioasForIdJokalaria3 = alineazioasForIdJokalaria3;
	}

	public Set getAlineazioasForIdJokalaria2() {
		return this.alineazioasForIdJokalaria2;
	}

	public void setAlineazioasForIdJokalaria2(Set alineazioasForIdJokalaria2) {
		this.alineazioasForIdJokalaria2 = alineazioasForIdJokalaria2;
	}

	public Set getMerkatukoJokalarias() {
		return this.merkatukoJokalarias;
	}

	public void setMerkatukoJokalarias(Set merkatukoJokalarias) {
		this.merkatukoJokalarias = merkatukoJokalarias;
	}

	public Set getAlineazioasForIdJokalaria1() {
		return this.alineazioasForIdJokalaria1;
	}

	public void setAlineazioasForIdJokalaria1(Set alineazioasForIdJokalaria1) {
		this.alineazioasForIdJokalaria1 = alineazioasForIdJokalaria1;
	}

}
