package domain;
// Generated 08-may-2019 9:56:30 by Hibernate Tools 5.4.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.Iterator;
import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * MerkatukoJokalaria generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class MerkatukoJokalaria implements Serializable {

	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private Integer idMerkatukoJokalaria=0;
	
	@XmlIDREF private Erabiltzailea erabiltzaileaByIdErabiltzaileaIrabazlea=new Erabiltzailea();
	@XmlIDREF private Erabiltzailea erabiltzaileaByIdErabiltzaileaJabea=new Erabiltzailea();
	
	private Jokalaria jokalaria=new Jokalaria();
	@XmlIDREF private Komunitatea komunitatea=new Komunitatea();
	
	private int hasierakoPrezioa=0;
	private int eskaintzaIrabazlea=0;
	private boolean onartua=false;
	private boolean tramitatua=false;
	private Date tramitazioEguna=new Date();
	
	@XmlIDREF private Set eskaintzas = new HashSet(0);

	public MerkatukoJokalaria() {
	}
	
	public MerkatukoJokalaria getKopia() {
		MerkatukoJokalaria res=new MerkatukoJokalaria();
		res.setIdMerkatukoJokalaria(idMerkatukoJokalaria);
		if(erabiltzaileaByIdErabiltzaileaIrabazlea!=null) {
			res.setErabiltzaileaByIdErabiltzaileaIrabazlea(erabiltzaileaByIdErabiltzaileaIrabazlea.getKopia());
		}else {
			res.setErabiltzaileaByIdErabiltzaileaIrabazlea(new Erabiltzailea());
		}
		if(erabiltzaileaByIdErabiltzaileaJabea!=null) {
			res.setErabiltzaileaByIdErabiltzaileaJabea(erabiltzaileaByIdErabiltzaileaJabea.getKopia());
		}else {
			res.setErabiltzaileaByIdErabiltzaileaJabea(new Erabiltzailea());
		}
		res.setJokalaria(jokalaria.getKopia());
		res.setKomunitatea(komunitatea.getKopia());
		res.setHasierakoPrezioa(hasierakoPrezioa);
		res.setEskaintzaIrabazlea(eskaintzaIrabazlea);
		res.setOnartua(onartua);
		res.setTramitatua(tramitatua);
		res.setTramitazioEguna(tramitazioEguna);
		/*Iterator itr =this.getEskaintzas().iterator();
		while(itr.hasNext()) {
			System.out.println("a");
			res.getEskaintzas().add(((Eskaintza)itr.next()).getKopia());
		}*/
		return res;
	}
	
	public MerkatukoJokalaria(int idMerkatukoJokalaria) {
		this.idMerkatukoJokalaria=idMerkatukoJokalaria;
	}

	public MerkatukoJokalaria(Erabiltzailea erabiltzaileaByIdErabiltzaileaIrabazlea,
			Erabiltzailea erabiltzaileaByIdErabiltzaileaJabea, Jokalaria jokalaria, Komunitatea komunitatea,
			int hasierakoPrezioa, int eskaintzaIrabazlea, boolean onartua, boolean tramitatua, Date tramitazioEguna) {
		this.erabiltzaileaByIdErabiltzaileaIrabazlea = erabiltzaileaByIdErabiltzaileaIrabazlea;
		this.erabiltzaileaByIdErabiltzaileaJabea = erabiltzaileaByIdErabiltzaileaJabea;
		this.jokalaria = jokalaria;
		this.komunitatea = komunitatea;
		this.hasierakoPrezioa = hasierakoPrezioa;
		this.eskaintzaIrabazlea = eskaintzaIrabazlea;
		this.onartua = onartua;
		this.tramitatua = tramitatua;
		this.tramitazioEguna = tramitazioEguna;
	}

	public MerkatukoJokalaria(Erabiltzailea erabiltzaileaByIdErabiltzaileaIrabazlea,
			Erabiltzailea erabiltzaileaByIdErabiltzaileaJabea, Jokalaria jokalaria, Komunitatea komunitatea,
			int hasierakoPrezioa, int eskaintzaIrabazlea, boolean onartua, boolean tramitatua, Date tramitazioEguna,
			Set eskaintzas) {
		this.erabiltzaileaByIdErabiltzaileaIrabazlea = erabiltzaileaByIdErabiltzaileaIrabazlea;
		this.erabiltzaileaByIdErabiltzaileaJabea = erabiltzaileaByIdErabiltzaileaJabea;
		this.jokalaria = jokalaria;
		this.komunitatea = komunitatea;
		this.hasierakoPrezioa = hasierakoPrezioa;
		this.eskaintzaIrabazlea = eskaintzaIrabazlea;
		this.onartua = onartua;
		this.tramitatua = tramitatua;
		this.tramitazioEguna = tramitazioEguna;
		this.eskaintzas = eskaintzas;
	}
	

	public Integer getIdMerkatukoJokalaria() {
		return this.idMerkatukoJokalaria;
	}

	public void setIdMerkatukoJokalaria(Integer idMerkatukoJokalaria) {
		this.idMerkatukoJokalaria = idMerkatukoJokalaria;
	}

	public Erabiltzailea getErabiltzaileaByIdErabiltzaileaIrabazlea() {
		return this.erabiltzaileaByIdErabiltzaileaIrabazlea;
	}

	public void setErabiltzaileaByIdErabiltzaileaIrabazlea(Erabiltzailea erabiltzaileaByIdErabiltzaileaIrabazlea) {
		this.erabiltzaileaByIdErabiltzaileaIrabazlea = erabiltzaileaByIdErabiltzaileaIrabazlea;
	}

	public Erabiltzailea getErabiltzaileaByIdErabiltzaileaJabea() {
		return this.erabiltzaileaByIdErabiltzaileaJabea;
	}

	public void setErabiltzaileaByIdErabiltzaileaJabea(Erabiltzailea erabiltzaileaByIdErabiltzaileaJabea) {
		this.erabiltzaileaByIdErabiltzaileaJabea = erabiltzaileaByIdErabiltzaileaJabea;
	}

	public Jokalaria getJokalaria() {
		return this.jokalaria;
	}

	public void setJokalaria(Jokalaria jokalaria) {
		this.jokalaria = jokalaria;
	}

	public Komunitatea getKomunitatea() {
		return this.komunitatea;
	}

	public void setKomunitatea(Komunitatea komunitatea) {
		this.komunitatea = komunitatea;
	}

	public int getHasierakoPrezioa() {
		return this.hasierakoPrezioa;
	}

	public void setHasierakoPrezioa(int hasierakoPrezioa) {
		this.hasierakoPrezioa = hasierakoPrezioa;
	}

	public int getEskaintzaIrabazlea() {
		return this.eskaintzaIrabazlea;
	}

	public void setEskaintzaIrabazlea(int eskaintzaIrabazlea) {
		this.eskaintzaIrabazlea = eskaintzaIrabazlea;
	}

	public boolean isOnartua() {
		return this.onartua;
	}

	public void setOnartua(boolean onartua) {
		this.onartua = onartua;
	}

	public boolean isTramitatua() {
		return this.tramitatua;
	}

	public void setTramitatua(boolean tramitatua) {
		this.tramitatua = tramitatua;
	}

	public Date getTramitazioEguna() {
		return this.tramitazioEguna;
	}

	public void setTramitazioEguna(Date tramitazioEguna) {
		this.tramitazioEguna = tramitazioEguna;
	}

	public Set getEskaintzas() {
		return this.eskaintzas;
	}

	public void setEskaintzas(Set eskaintzas) {
		this.eskaintzas = eskaintzas;
	}

}
