package domain;
// Generated 08-may-2019 9:56:30 by Hibernate Tools 5.4.1.Final

import java.util.Date;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Mezua generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class Mezua implements java.io.Serializable {

	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private Integer idMezua=0;
	
	@XmlIDREF private Erabiltzailea erabiltzailea=new Erabiltzailea();
	@XmlIDREF private Komunitatea komunitatea=new Komunitatea();
	
	private Date eguna=new Date();
	private Boolean ezabagarria=true;
	private String mezua="";

	public Mezua() {
	}
	
	public Mezua getKopia() {
		Mezua res=new Mezua();
		res.setIdMezua(idMezua);
		res.setErabiltzailea(erabiltzailea.getKopia());
		res.setKomunitatea(komunitatea.getKopia());
		res.setEguna(eguna);
		res.setEzabagarria(ezabagarria);
		res.setMezua(mezua);
		return res;
	}

	public Mezua(Erabiltzailea erabiltzailea, Komunitatea komunitatea, Date eguna, Boolean ezabagarria, String mezua) {
		this.erabiltzailea = erabiltzailea;
		this.komunitatea = komunitatea;
		this.eguna = eguna;
		this.ezabagarria = ezabagarria;
		this.mezua = mezua;
	}

	public Integer getIdMezua() {
		return this.idMezua;
	}

	public void setIdMezua(Integer idMezua) {
		this.idMezua = idMezua;
	}

	public Erabiltzailea getErabiltzailea() {
		return this.erabiltzailea;
	}

	public void setErabiltzailea(Erabiltzailea erabiltzailea) {
		this.erabiltzailea = erabiltzailea;
	}

	public Komunitatea getKomunitatea() {
		return this.komunitatea;
	}

	public void setKomunitatea(Komunitatea komunitatea) {
		this.komunitatea = komunitatea;
	}

	public Date getEguna() {
		return this.eguna;
	}

	public void setEguna(Date eguna) {
		this.eguna = eguna;
	}

	public Boolean getEzabagarria() {
		return this.ezabagarria;
	}

	public void setEzabagarria(Boolean ezabagarria) {
		this.ezabagarria = ezabagarria;
	}

	public String getMezua() {
		return this.mezua;
	}

	public void setMezua(String mezua) {
		this.mezua = mezua;
	}

}
