package domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * PuntuazioaErabiltzaileaJardunaldiaId generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class PuntuazioaErabiltzaileaJardunaldiaId implements java.io.Serializable {

	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private int idErabiltzailea;
	
	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private int idJardunaldia;

	public PuntuazioaErabiltzaileaJardunaldiaId() {
	}

	public PuntuazioaErabiltzaileaJardunaldiaId(int idErabiltzailea, int idJardunaldia) {
		this.idErabiltzailea = idErabiltzailea;
		this.idJardunaldia = idJardunaldia;
	}

	public int getIdErabiltzailea() {
		return this.idErabiltzailea;
	}

	public void setIdErabiltzailea(int idErabiltzailea) {
		this.idErabiltzailea = idErabiltzailea;
	}

	public int getIdJardunaldia() {
		return this.idJardunaldia;
	}

	public void setIdJardunaldia(int idJardunaldia) {
		this.idJardunaldia = idJardunaldia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PuntuazioaErabiltzaileaJardunaldiaId))
			return false;
		PuntuazioaErabiltzaileaJardunaldiaId castOther = (PuntuazioaErabiltzaileaJardunaldiaId) other;

		return (this.getIdErabiltzailea() == castOther.getIdErabiltzailea())
				&& (this.getIdJardunaldia() == castOther.getIdJardunaldia());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdErabiltzailea();
		result = 37 * result + this.getIdJardunaldia();
		return result;
	}

}
class PuntuazioaErabiltzaileaJardunaldiaIdAdapter extends XmlAdapter<String, PuntuazioaErabiltzaileaJardunaldiaId> {
    
    public PuntuazioaErabiltzaileaJardunaldiaId unmarshal(String s) {
    	return new PuntuazioaErabiltzaileaJardunaldiaId(Integer.parseInt(s.split("_")[0]),Integer.parseInt(s.split("_")[1]));
    }

	@Override
	public String marshal(PuntuazioaErabiltzaileaJardunaldiaId v) throws Exception {
		if (v == null) return "";
		
		return v.getIdErabiltzailea()+"_"+v.getIdJardunaldia();
	}
}
