package domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import java.io.Serializable;
import java.util.Comparator;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * PuntuazioaErabiltzaileaJardunaldia generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class PuntuazioaErabiltzaileaJardunaldia implements Serializable{

	@XmlID
	@XmlJavaTypeAdapter(PuntuazioaErabiltzaileaJardunaldiaIdAdapter.class)
	@Id
	@GeneratedValue
	private PuntuazioaErabiltzaileaJardunaldiaId id;
	
	private Erabiltzailea erabiltzailea;
	@XmlIDREF private Jardunaldia jardunaldia;
	
	private Integer puntuak=0;

	public PuntuazioaErabiltzaileaJardunaldia() {
	}
	
	public PuntuazioaErabiltzaileaJardunaldia getKopia() {
		PuntuazioaErabiltzaileaJardunaldia res=new PuntuazioaErabiltzaileaJardunaldia();
		res.setId(id);
		res.setErabiltzailea(erabiltzailea.getKopia());
		res.setJardunaldia(jardunaldia.getKopia());
		res.setPuntuak(puntuak);
		return res;
	}

	public PuntuazioaErabiltzaileaJardunaldia(PuntuazioaErabiltzaileaJardunaldiaId id, Erabiltzailea erabiltzailea,
			Jardunaldia jardunaldia) {
		this.id = id;
		this.erabiltzailea = erabiltzailea;
		this.jardunaldia = jardunaldia;
	}

	public PuntuazioaErabiltzaileaJardunaldia(PuntuazioaErabiltzaileaJardunaldiaId id, Erabiltzailea erabiltzailea,
			Jardunaldia jardunaldia, Integer puntuak) {
		this.id = id;
		this.erabiltzailea = erabiltzailea;
		this.jardunaldia = jardunaldia;
		this.puntuak = puntuak;
	}

	public PuntuazioaErabiltzaileaJardunaldiaId getId() {
		return this.id;
	}

	public void setId(PuntuazioaErabiltzaileaJardunaldiaId id) {
		this.id = id;
	}

	public Erabiltzailea getErabiltzailea() {
		return this.erabiltzailea;
	}

	public void setErabiltzailea(Erabiltzailea erabiltzailea) {
		this.erabiltzailea = erabiltzailea;
	}

	public Jardunaldia getJardunaldia() {
		return this.jardunaldia;
	}

	public void setJardunaldia(Jardunaldia jardunaldia) {
		this.jardunaldia = jardunaldia;
	}

	public Integer getPuntuak() {
		return this.puntuak;
	}

	public void setPuntuak(Integer puntuak) {
		this.puntuak = puntuak;
	}



}
