package domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * PuntuazioaJokalariaJardunaldiaId generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class PuntuazioaJokalariaJardunaldiaId implements Serializable {

	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private int idJokalaria;
	
	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private int idJardunaldia;

	public PuntuazioaJokalariaJardunaldiaId() {
	}

	public PuntuazioaJokalariaJardunaldiaId(int idJokalaria, int idJardunaldia) {
		this.idJokalaria = idJokalaria;
		this.idJardunaldia = idJardunaldia;
	}

	public int getIdJokalaria() {
		return this.idJokalaria;
	}

	public void setIdJokalaria(int idJokalaria) {
		this.idJokalaria = idJokalaria;
	}

	public int getIdJardunaldia() {
		return this.idJardunaldia;
	}

	public void setIdJardunaldia(int idJardunaldia) {
		this.idJardunaldia = idJardunaldia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PuntuazioaJokalariaJardunaldiaId))
			return false;
		PuntuazioaJokalariaJardunaldiaId castOther = (PuntuazioaJokalariaJardunaldiaId) other;

		return (this.getIdJokalaria() == castOther.getIdJokalaria())
				&& (this.getIdJardunaldia() == castOther.getIdJardunaldia());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdJokalaria();
		result = 37 * result + this.getIdJardunaldia();
		return result;
	}

}
class PuntuazioaJokalariaJardunaldiaIdAdapter extends XmlAdapter<String, PuntuazioaJokalariaJardunaldiaId> {
    
    public PuntuazioaJokalariaJardunaldiaId unmarshal(String s) {
    	return new PuntuazioaJokalariaJardunaldiaId(Integer.parseInt(s.split("_")[0]),Integer.parseInt(s.split("_")[1]));
    }
 
	@Override
	public String marshal(PuntuazioaJokalariaJardunaldiaId p) throws Exception {
		if (p == null) return "";
		
		return p.getIdJokalaria()+"_"+p.getIdJardunaldia();
	}

}
