package domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import java.util.Date;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Transakzioa generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class Transakzioa implements Serializable {

	@XmlID
	@XmlJavaTypeAdapter(IntegerAdapter.class)
	@Id
	@GeneratedValue
	private Integer idTransakzioa=0;
	
	@XmlIDREF
	private Erabiltzailea erabiltzailea=new Erabiltzailea();
	private Integer kantitatea=0;
	private String mezua="";
	private Date eguna=new Date();

	public Transakzioa() {
	}
	
	public Transakzioa getKopia() {
		Transakzioa res=new Transakzioa();
		res.setIdTransakzioa(idTransakzioa);
		res.setErabiltzailea(erabiltzailea.getKopia());
		res.setKantitatea(kantitatea);
		res.setMezua(mezua);
		res.setEguna(eguna);
		return res;
	}
	

	public Transakzioa(Erabiltzailea erabiltzailea, Integer kantitatea, String mezua, Date eguna) {
		this.erabiltzailea = erabiltzailea;
		this.kantitatea = kantitatea;
		this.mezua = mezua;
		this.eguna = eguna;
	}

	public Integer getIdTransakzioa() {
		return this.idTransakzioa;
	}

	public void setIdTransakzioa(Integer idTransakzioa) {
		this.idTransakzioa = idTransakzioa;
	}

	public Erabiltzailea getErabiltzailea() {
		return this.erabiltzailea;
	}

	public void setErabiltzailea(Erabiltzailea erabiltzailea) {
		this.erabiltzailea = erabiltzailea;
	}

	public Integer getKantitatea() {
		return this.kantitatea;
	}

	public void setKantitatea(Integer kantitatea) {
		this.kantitatea = kantitatea;
	}

	public String getMezua() {
		return this.mezua;
	}

	public void setMezua(String mezua) {
		this.mezua = mezua;
	}

	public Date getEguna() {
		return this.eguna;
	}

	public void setEguna(Date eguna) {
		this.eguna = eguna;
	}

}
