package com.jgr14.nbasaresoziala.domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.HashSet;
import java.util.Hashtable;
import java.util.Set;

import java.io.Serializable;



/**
 * Erabiltzailea generated by hbm2java
 */
public class Erabiltzailea implements Serializable,KvmSerializable {

	private Integer idErabiltzailea=0;
	
	private Komunitatea komunitatea=new Komunitatea();
	
	private String nick="";
	private String email="";
	private String pasahitza="";
	private String izenOsoa="";
	private int dirua=0;
	private boolean administratzailea=false;
	private String hizkuntza="";
	private int koloreak=0;
	private int orduDiferentzia=0;
	
	private Set jokalarias = new HashSet(0);
	private Set puntuazioaErabiltzaileaJardunaldias = new HashSet(0);
	private Set merkatukoJokalariasForIdErabiltzaileaEskaintzaHandiena = new HashSet(0);
	private Set merkatukoJokalariasForIdErabiltzaileaJabea = new HashSet(0);
	private Set mezuas = new HashSet(0);
	private Set transakzioas = new HashSet(0);
	private Set alineazioas = new HashSet(0);

	public Erabiltzailea() {
	}

	public Erabiltzailea(int idErabiltzailea) {
		this.idErabiltzailea=idErabiltzailea;
	}
	public Erabiltzailea(int idErabiltzailea,String nick) {
		this.idErabiltzailea=idErabiltzailea;
		this.nick=nick;
	}

	public Erabiltzailea(String nick, String email, String pasahitza, String izenOsoa, int dirua,
			boolean administratzailea, String hizkuntza, int koloreak, int orduDiferentzia) {
		this.nick = nick;
		this.email = email;
		this.pasahitza = pasahitza;
		this.izenOsoa = izenOsoa;
		this.dirua = dirua;
		this.administratzailea = administratzailea;
		this.hizkuntza = hizkuntza;
		this.koloreak = koloreak;
		this.orduDiferentzia = orduDiferentzia;
	}

	public Erabiltzailea(Komunitatea komunitatea, String nick, String email, String pasahitza, String izenOsoa,
			int dirua, boolean administratzailea, String hizkuntza, int koloreak, int orduDiferentzia, Set jokalarias,
			Set puntuazioaErabiltzaileaJardunaldias, Set merkatukoJokalariasForIdErabiltzaileaEskaintzaHandiena,
			Set merkatukoJokalariasForIdErabiltzaileaJabea, Set mezuas, Set transakzioas, Set alineazioas) {
		this.komunitatea = komunitatea;
		this.nick = nick;
		this.email = email;
		this.pasahitza = pasahitza;
		this.izenOsoa = izenOsoa;
		this.dirua = dirua;
		this.administratzailea = administratzailea;
		this.hizkuntza = hizkuntza;
		this.koloreak = koloreak;
		this.orduDiferentzia = orduDiferentzia;
		this.jokalarias = jokalarias;
		this.puntuazioaErabiltzaileaJardunaldias = puntuazioaErabiltzaileaJardunaldias;
		this.merkatukoJokalariasForIdErabiltzaileaEskaintzaHandiena = merkatukoJokalariasForIdErabiltzaileaEskaintzaHandiena;
		this.merkatukoJokalariasForIdErabiltzaileaJabea = merkatukoJokalariasForIdErabiltzaileaJabea;
		this.mezuas = mezuas;
		this.transakzioas = transakzioas;
		this.alineazioas = alineazioas;
	}


	@Override
	public Object getProperty(int i) {
		switch (i){
			case 0: return idErabiltzailea;
			case 1: return nick;
			case 2: return email;
			case 3: return pasahitza;
			case 4: return izenOsoa;
			case 5: return dirua;
			case 6: return administratzailea;
			case 7: return hizkuntza;
			case 8: return koloreak;
			case 9: return orduDiferentzia;
		}
		return null;
	}

	@Override
	public int getPropertyCount() {
		return 10;
	}

	@Override
	public void setProperty(int i, Object o) {
		switch (i){
			case 0: idErabiltzailea=Integer.parseInt(o.toString());break;
			case 1: nick=o.toString();break;
			case 2: email=o.toString();break;
			case 3: pasahitza=o.toString();break;
			case 4: izenOsoa=o.toString();break;
			case 5: dirua=Integer.parseInt(o.toString());break;
			case 6: administratzailea=Boolean.parseBoolean(o.toString());break;
			case 7: hizkuntza=o.toString();break;
			case 8: koloreak=Integer.parseInt(o.toString());break;
			case 9: orduDiferentzia=Integer.parseInt(o.toString());break;
		}
	}
	@Override
	public void getPropertyInfo(int i, Hashtable properties, PropertyInfo info) {
		switch (i){
			case 0:info.name="idErabiltzailea";info.type = PropertyInfo.INTEGER_CLASS;break;
			case 1:info.name="nick";info.type = PropertyInfo.STRING_CLASS;break;
			case 2:info.name="email";info.type = PropertyInfo.STRING_CLASS;break;
			case 3:info.name="pasahitza";info.type = PropertyInfo.STRING_CLASS;break;
			case 4:info.name="izenOsoa";info.type = PropertyInfo.STRING_CLASS;break;
			case 5:info.name="dirua";info.type = PropertyInfo.INTEGER_CLASS;break;
			case 6:info.name="administratzailea";info.type = PropertyInfo.BOOLEAN_CLASS;break;
			case 7:info.name="hizkuntza";info.type = PropertyInfo.STRING_CLASS;break;
			case 8:info.name="koloreak";info.type = PropertyInfo.INTEGER_CLASS;break;
			case 9:info.name="orduDiferentzia";info.type = PropertyInfo.INTEGER_CLASS;break;
		}
	}

	public String diruaFormatuarekin(){
		try{
			String salarioLag=""+this.dirua;
			String salario="";
			while(salarioLag.length()>3) {
				salario=salario+","+salarioLag.substring(salarioLag.length()-3,salarioLag.length());
				salarioLag=salarioLag.substring(0,salarioLag.length()-3);
			}
			salario="$"+salarioLag+salario;
			return salario;

		}catch (Exception e){
			e.printStackTrace();
			return "";
		}
	}

	public Integer getIdErabiltzailea() {
		return this.idErabiltzailea;
	}

	public void setIdErabiltzailea(Integer idErabiltzailea) {
		this.idErabiltzailea = idErabiltzailea;
	}

	public Komunitatea getKomunitatea() {
		
		return this.komunitatea;
	}

	public void setKomunitatea(Komunitatea komunitatea) {
		this.komunitatea = komunitatea;
	}

	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasahitza() {
		return this.pasahitza;
	}

	public void setPasahitza(String pasahitza) {
		this.pasahitza = pasahitza;
	}

	public String getIzenOsoa() {
		return this.izenOsoa;
	}

	public void setIzenOsoa(String izenOsoa) {
		this.izenOsoa = izenOsoa;
	}

	public int getDirua() {
		return this.dirua;
	}

	public void setDirua(int dirua) {
		this.dirua = dirua;
	}

	public boolean isAdministratzailea() {
		return this.administratzailea;
	}

	public void setAdministratzailea(boolean administratzailea) {
		this.administratzailea = administratzailea;
	}

	public String getHizkuntza() {
		return this.hizkuntza;
	}

	public void setHizkuntza(String hizkuntza) {
		this.hizkuntza = hizkuntza;
	}

	public int getKoloreak() {
		return this.koloreak;
	}

	public void setKoloreak(int koloreak) {
		this.koloreak = koloreak;
	}

	public int getOrduDiferentzia() {
		return this.orduDiferentzia;
	}

	public void setOrduDiferentzia(int orduDiferentzia) {
		this.orduDiferentzia = orduDiferentzia;
	}

	public Set getJokalarias() {
		return this.jokalarias;
	}

	public void setJokalarias(Set jokalarias) {
		this.jokalarias = jokalarias;
	}

	public Set getPuntuazioaErabiltzaileaJardunaldias() {
		return this.puntuazioaErabiltzaileaJardunaldias;
	}

	public void setPuntuazioaErabiltzaileaJardunaldias(Set puntuazioaErabiltzaileaJardunaldias) {
		this.puntuazioaErabiltzaileaJardunaldias = puntuazioaErabiltzaileaJardunaldias;
	}

	public Set getMerkatukoJokalariasForIdErabiltzaileaEskaintzaHandiena() {
		return this.merkatukoJokalariasForIdErabiltzaileaEskaintzaHandiena;
	}

	public void setMerkatukoJokalariasForIdErabiltzaileaEskaintzaHandiena(
			Set merkatukoJokalariasForIdErabiltzaileaEskaintzaHandiena) {
		this.merkatukoJokalariasForIdErabiltzaileaEskaintzaHandiena = merkatukoJokalariasForIdErabiltzaileaEskaintzaHandiena;
	}

	public Set getMerkatukoJokalariasForIdErabiltzaileaJabea() {
		return this.merkatukoJokalariasForIdErabiltzaileaJabea;
	}

	public void setMerkatukoJokalariasForIdErabiltzaileaJabea(Set merkatukoJokalariasForIdErabiltzaileaJabea) {
		this.merkatukoJokalariasForIdErabiltzaileaJabea = merkatukoJokalariasForIdErabiltzaileaJabea;
	}

	public Set getMezuas() {
		return this.mezuas;
	}

	public void setMezuas(Set mezuas) {
		this.mezuas = mezuas;
	}

	public Set getTransakzioas() {
		return this.transakzioas;
	}

	public void setTransakzioas(Set transakzioas) {
		this.transakzioas = transakzioas;
	}

	public Set getAlineazioas() {
		return this.alineazioas;
	}

	public void setAlineazioas(Set alineazioas) {
		this.alineazioas = alineazioas;
	}


}
