package com.jgr14.nbasaresoziala.domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Date;
import java.util.HashSet;
import java.util.Hashtable;
import java.util.Set;

import java.io.Serializable;

/**
 * Jardunaldia generated by hbm2java
 */
public class Jardunaldia implements Serializable,KvmSerializable {

	private Integer idJardunaldia;
	private Date hasierakoEguna;
	
	private Set puntuazioaJokalariaJardunaldias = new HashSet(0);
	private Set puntuazioaErabiltzaileaJardunaldias = new HashSet(0);

	public Jardunaldia() {
	}
	public Jardunaldia(int idJardunaldia) {
		this.idJardunaldia=idJardunaldia;
	}

	public Jardunaldia(Date hasierakoEguna, Set puntuazioaJokalariaJardunaldias,
			Set puntuazioaErabiltzaileaJardunaldias) {
		this.hasierakoEguna = hasierakoEguna;
		this.puntuazioaJokalariaJardunaldias = puntuazioaJokalariaJardunaldias;
		this.puntuazioaErabiltzaileaJardunaldias = puntuazioaErabiltzaileaJardunaldias;
	}

	public Integer getIdJardunaldia() {
		return this.idJardunaldia;
	}

	public void setIdJardunaldia(Integer idJardunaldia) {
		this.idJardunaldia = idJardunaldia;
	}

	public Date getHasierakoEguna() {
		return this.hasierakoEguna;
	}

	public void setHasierakoEguna(Date hasierakoEguna) {
		this.hasierakoEguna = hasierakoEguna;
	}

	public Set getPuntuazioaJokalariaJardunaldias() {
		return this.puntuazioaJokalariaJardunaldias;
	}

	public void setPuntuazioaJokalariaJardunaldias(Set puntuazioaJokalariaJardunaldias) {
		this.puntuazioaJokalariaJardunaldias = puntuazioaJokalariaJardunaldias;
	}

	public Set getPuntuazioaErabiltzaileaJardunaldias() {
		return this.puntuazioaErabiltzaileaJardunaldias;
	}

	public void setPuntuazioaErabiltzaileaJardunaldias(Set puntuazioaErabiltzaileaJardunaldias) {
		this.puntuazioaErabiltzaileaJardunaldias = puntuazioaErabiltzaileaJardunaldias;
	}

	@Override
	public Object getProperty(int i) {
		switch (i) {
			case 0: return idJardunaldia;
			case 1: return hasierakoEguna;
		}
		return null;
	}

	@Override
	public int getPropertyCount() {
		return 2;
	}

	@Override
	public void setProperty(int i, Object o) {
		switch (i){
			case 0: idJardunaldia=Integer.parseInt(o.toString());break;
			case 1: hasierakoEguna=(Date)o;break;
		}
	}

	@Override
	public void getPropertyInfo(int i, Hashtable properties, PropertyInfo info) {
		switch (i){
			case 0:info.name="idJardunaldia";info.type = PropertyInfo.INTEGER_CLASS;break;
			case 1:info.name="hasierakoEguna";info.setType(Date.class);break;
		}
	}
}
