package com.jgr14.nbasaresoziala.domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import java.io.Serializable;



/**
 * PuntuazioaJokalariaJardunaldia generated by hbm2java
 */
public class PuntuazioaJokalariaJardunaldia implements java.io.Serializable {

	private Jardunaldia jardunaldia;
	private Jokalaria jokalaria;
	
	private Integer puntuak;
	
	
	 private int puntu_totalak;
	 private int partidu_kopurua;

	 public void puntuak_ezarri() {
	    	if(partidu_kopurua==0) {
	    		setPuntuak(0);
	    	}else {
	    		setPuntuak(puntu_totalak/partidu_kopurua);
	    	}
	    }

	    
	    @Override
	    public boolean equals(Object object){
	        boolean sameSame = false;

	        if (object != null && object instanceof PuntuazioaJokalariaJardunaldia){
	            sameSame = this.jokalaria.getIdJokalaria() == ((PuntuazioaJokalariaJardunaldia) object).jokalaria.getIdJokalaria();
	        }

	        return sameSame;
	    }
	    
	public int getIdJardunaldia() {
		return this.jardunaldia.getIdJardunaldia();
	}
	    
	public PuntuazioaJokalariaJardunaldia() {
	}

	public PuntuazioaJokalariaJardunaldia(Jardunaldia jardunaldia, Jokalaria jokalaria) {
		this.jardunaldia = jardunaldia;
		this.jokalaria = jokalaria;
	}

	public PuntuazioaJokalariaJardunaldia(Jardunaldia jardunaldia, Jokalaria jokalaria, Integer puntuak) {
		this.jardunaldia = jardunaldia;
		this.jokalaria = jokalaria;
		this.puntuak = puntuak;
	}

	public Jardunaldia getJardunaldia() {
		return this.jardunaldia;
	}

	public void setJardunaldia(Jardunaldia jardunaldia) {
		this.jardunaldia = jardunaldia;
	}

	public Jokalaria getJokalaria() {
		return this.jokalaria;
	}

	public void setJokalaria(Jokalaria jokalaria) {
		this.jokalaria = jokalaria;
	}

	public Integer getPuntuak() {
		return this.puntuak;
	}

	public void setPuntuak(Integer puntuak) {
		this.puntuak = puntuak;
	}


	public int getPuntu_totalak() {
		return puntu_totalak;
	}


	public int getPartidu_kopurua() {
		return partidu_kopurua;
	}


	public void setPuntu_totalak(int puntu_totalak) {
		this.puntu_totalak = puntu_totalak;
	}


	public void setPartidu_kopurua(int partidu_kopurua) {
		this.partidu_kopurua = partidu_kopurua;
	}

}
