package com.jgr14.nbasaresoziala.domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import java.io.Serializable;
import java.util.Comparator;


/**
 * PuntuazioaErabiltzaileaJardunaldia generated by hbm2java
 */
public class PuntuazioaErabiltzaileaJardunaldia implements Serializable{


	private Erabiltzailea erabiltzailea;
	private Jardunaldia jardunaldia;
	
	private Integer puntuak;

	public PuntuazioaErabiltzaileaJardunaldia() {
	}

	public PuntuazioaErabiltzaileaJardunaldia(Erabiltzailea erabiltzailea, Jardunaldia jardunaldia) {
		this.erabiltzailea = erabiltzailea;
		this.jardunaldia = jardunaldia;
	}

	public PuntuazioaErabiltzaileaJardunaldia(Erabiltzailea erabiltzailea, Jardunaldia jardunaldia, Integer puntuak) {
		this.erabiltzailea = erabiltzailea;
		this.jardunaldia = jardunaldia;
		this.puntuak = puntuak;
	}


	public Erabiltzailea getErabiltzailea() {
		return this.erabiltzailea;
	}

	public void setErabiltzailea(Erabiltzailea erabiltzailea) {
		this.erabiltzailea = erabiltzailea;
	}

	public Jardunaldia getJardunaldia() {
		return this.jardunaldia;
	}

	public void setJardunaldia(Jardunaldia jardunaldia) {
		this.jardunaldia = jardunaldia;
	}

	public Integer getPuntuak() {
		return this.puntuak;
	}

	public void setPuntuak(Integer puntuak) {
		this.puntuak = puntuak;
	}



}
