package com.jgr14.nbasaresoziala.domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import com.jgr14.nbasaresoziala.dataAccess.DataAccess;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.HashSet;
import java.util.Hashtable;
import java.util.Set;

import java.io.Serializable;

/**
 * Taldea generated by hbm2java
 */
public class Taldea implements Serializable,KvmSerializable {


	private Integer idTaldea=0;
	
	private String hiria="";
	private String apodoa="";
	private String izenOsoa="";
	private String konferentzia="";
	private String urlIzena="";
	
	private Set jokalariasForIdTaldea = new HashSet(0);
	private Set jokalariasForDraftIdTaldea = new HashSet(0);

	public Taldea() {
	}

	public Taldea(int idTaldea) {
		this.idTaldea = idTaldea;
	}

	public Taldea(int idTaldea, String hiria, String apodoa, String izenOsoa, String konferentzia, String urlIzena) {
		this.idTaldea = idTaldea;
		this.hiria = hiria;
		this.apodoa = apodoa;
		this.izenOsoa = izenOsoa;
		this.konferentzia = konferentzia;
		this.urlIzena = urlIzena;
	}

    public String getArgazkia(){
        return DataAccess.URL+":8080/nba_sare-soziala/img/taldea/"+idTaldea+".png";
    }


	@Override
	public Object getProperty(int i) {
		switch (i){
			case 0: return idTaldea;
			case 1: return hiria;
			case 2: return apodoa;
			case 3: return izenOsoa;
			case 4: return konferentzia;
			case 5: return urlIzena;
		}
		return null;
	}
	@Override
	public int getPropertyCount() {
		return 6;
	}
	@Override
	public void setProperty(int i, Object o) {
		switch (i){
			case 0: idTaldea=Integer.parseInt(o.toString());break;
			case 1: hiria=o.toString();break;
			case 2: apodoa=o.toString();break;
			case 3: izenOsoa=o.toString();break;
			case 4: konferentzia=o.toString();break;
			case 5: urlIzena=o.toString();break;
		}
	}

	@Override
	public void getPropertyInfo(int i, Hashtable properties, PropertyInfo info) {
		switch (i){
			case 0:info.name="idTaldea";info.type = PropertyInfo.INTEGER_CLASS;break;
			case 1:info.name="hiria";info.type = PropertyInfo.STRING_CLASS;break;
			case 2:info.name="apodoa";info.type = PropertyInfo.STRING_CLASS;break;
			case 3:info.name="izenOsoa";info.type = PropertyInfo.STRING_CLASS;break;
			case 4:info.name="konferentzia";info.type = PropertyInfo.STRING_CLASS;break;
			case 5:info.name="urlIzena";info.type = PropertyInfo.STRING_CLASS;break;
		}
	}





	public int getIdTaldea() {
		return this.idTaldea;
	}

	public void setIdTaldea(int idTaldea) {
		this.idTaldea = idTaldea;
	}

	public String getHiria() {
		return this.hiria;
	}

	public void setHiria(String hiria) {
		this.hiria = hiria;
	}

	public String getApodoa() {
		return this.apodoa;
	}

	public void setApodoa(String apodoa) {
		this.apodoa = apodoa;
	}

	public String getIzenOsoa() {
		return this.izenOsoa;
	}

	public void setIzenOsoa(String izenOsoa) {
		this.izenOsoa = izenOsoa;
	}

	public String getKonferentzia() {
		return this.konferentzia;
	}

	public void setKonferentzia(String konferentzia) {
		this.konferentzia = konferentzia;
	}

	public String getUrlIzena() {
		return this.urlIzena;
	}

	public void setUrlIzena(String urlIzena) {
		this.urlIzena = urlIzena;
	}

	public Set getJokalariasForIdTaldea() {
		return this.jokalariasForIdTaldea;
	}

	public void setJokalariasForIdTaldea(Set jokalariasForIdTaldea) {
		this.jokalariasForIdTaldea = jokalariasForIdTaldea;
	}

	public Set getJokalariasForDraftIdTaldea() {
		return this.jokalariasForDraftIdTaldea;
	}

	public void setJokalariasForDraftIdTaldea(Set jokalariasForDraftIdTaldea) {
		this.jokalariasForDraftIdTaldea = jokalariasForDraftIdTaldea;
	}


}
