package com.jgr14.nbasaresoziala.domain;
// Generated 06-mar-2019 12:17:39 by Hibernate Tools 5.4.1.Final

import android.app.Activity;

import com.jgr14.nbasaresoziala.R;

import java.util.Date;

import java.io.Serializable;

/**
 * Transakzioa generated by hbm2java
 */
public class Transakzioa implements Serializable {

	private Integer idTransakzioa=0;
	
	private Erabiltzailea erabiltzailea=new Erabiltzailea();
	private Integer kantitatea=0;
	private String mezua="";
	private Date eguna=new Date();

	public Transakzioa() {
	}

	public Transakzioa(Erabiltzailea erabiltzailea, Integer kantitatea, String mezua, Date eguna) {
		this.erabiltzailea = erabiltzailea;
		this.kantitatea = kantitatea;
		this.mezua = mezua;
		this.eguna = eguna;
	}

	public Integer getIdTransakzioa() {
		return this.idTransakzioa;
	}

	public void setIdTransakzioa(Integer idTransakzioa) {
		this.idTransakzioa = idTransakzioa;
	}

	public Erabiltzailea getErabiltzailea() {
		return this.erabiltzailea;
	}

	public void setErabiltzailea(Erabiltzailea erabiltzailea) {
		this.erabiltzailea = erabiltzailea;
	}

	public Integer getKantitatea() {
		return this.kantitatea;
	}

	public void setKantitatea(Integer kantitatea) {
		this.kantitatea = kantitatea;
	}

	public String getMezua() {
		return this.mezua;
	}

	public void setMezua(String mezua) {
		this.mezua = mezua;
	}

	public Date getEguna() {
		return this.eguna;
	}

	public void setEguna(Date eguna) {
		this.eguna = eguna;
	}


	public String kantitateaFormatuarekin(){
		try{
			String salarioLag=""+this.kantitatea;
			String salario="";
			while(salarioLag.length()>3) {
				salario=salario+","+salarioLag.substring(salarioLag.length()-3,salarioLag.length());
				salarioLag=salarioLag.substring(0,salarioLag.length()-3);
			}
			salario="$"+salarioLag+salario;
			return salario;

		}catch (Exception e){
			e.printStackTrace();
			return "";
		}
	}


	public String getMezua(Activity activity){
		try{
			int mezu_id=Integer.parseInt(this.mezua.split("_")[0]);
			switch (mezu_id){
				case 0:return activity.getString(R.string.ongietorri_bonusa);
				case 1:return activity.getString(R.string.jornadako_saria1);
				case 2:return activity.getString(R.string.jornadako_saria2);
				case 3:return activity.getString(R.string.jornadako_saria3);
				case 4:return activity.getString(R.string.jokalaria_erosi)+": "+this.mezua.split("_")[1];
				case 5:return activity.getString(R.string.jokalaria_saldu)+": "+this.mezua.split("_")[1];
			}
		}catch (Exception e){
			e.printStackTrace();
		}
		return "";
	}

}
